name = 'Self Avoiding Walk II'
description = 'https://Glitch.com/~self-avoiding-walk-ii-pyscript'
version = 'v1.1.8'
author_name = 'GoToLoop'
license = 'Unlicense'

[[fetch]]

files = [
  'app/sketch.py',

  'modules/grid.py',
  'modules/spot.py',
  'modules/step.py',

  'utils/attribute.py',
  'utils/color.py',
  'utils/discover.py',
  'utils/size.py'
]
